sudo: required
language: node
services:
  - docker

before_install:
  - npm run docker-build

script:
  - npm run docker-test
  - ./tools/pr_preview.sh

addons:
  artifacts:
    s3_region: "eu-west-1"
    paths:
      - "docs"
